app/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

app/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('products/', views.total_products, name='total_products'),
    path('item/<id>/', views.detail_product, name='detail_product'),
    path('item/<slug:bike_slug>/', views.detail_product, name='bikes_list'),
]

app/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
from django.urls import reverse


class Company(models.Model):
    company_name = models.CharField(max_length=255, db_index=True)
    company_slug = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "1. Companies"

    def __str__(self):
        return self.company_name


class Bikes(models.Model):
    bike_name = models.CharField(max_length=255, db_index=True, null=True)
    bike_slug = models.SlugField(max_length=255, unique=True, null=True)
    company_name = models.ForeignKey(Company, related_name='company', on_delete=models.CASCADE, null=True)
    status = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "2. Bikes"
        ordering = ('-created',)

    def __str__(self):
        return self.bike_name


class Manufacturer(models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    manufacturer_name = models.CharField(max_length=255, db_index=True, null=True)
    manufacturer_slug = models.SlugField(max_length=255, unique=True, null=True)
    status = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "3. Manufacturer"
        ordering = ('-created',)

    def __str__(self):
        return self.manufacturer_name


class Supplier(models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    supplier_name = models.CharField(max_length=255, help_text='supplier Name')
    supplier_slug = models.SlugField(max_length=255, unique=True, null=True)
    manufacturer_name = models.ForeignKey(Manufacturer, related_name='manufacturer', on_delete=models.CASCADE,
                                          null=True)
    account_no = models.CharField(max_length=255,null=True,blank=True)
    pan_no = models.CharField(max_length=255,null=True,blank=True)
    gst_no = models.CharField(max_length=255,null=True,blank=True)
    cin_no = models.CharField(max_length=255,null=True,blank=True)
    status = models.CharField(max_length=10, choices=choices, default='1')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "4. Supplier"
        ordering = ('-created',)

    def __str__(self):
        return self.supplier_name


class Catelogue(models.Model):
    part_name = models.CharField(max_length=255)
    part_slug = models.SlugField(max_length=255, unique=True, null=True)
    part_number = models.CharField(max_length=255)
    part_for_bike = models.ForeignKey(Bikes, related_name='bike', on_delete=models.CASCADE, null=True)
    part_manufacturer = models.ForeignKey(Manufacturer, related_name='product_manufacturer', on_delete=models.CASCADE,
                                          null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)
    item_Description = models.TextField(blank=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='catlogue_added_by', on_delete=models.CASCADE, null=True)
    photo = models.ImageField(blank=True, upload_to="product_images/")  # storing links in database
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "5. Catelogue"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.part_slug])

    def __str__(self):
        return str(self.part_name)


class Invoice(models.Model):
    invoice_number = models.CharField(max_length=255)
    invoice_date = models.DateField()
    file = models.FileField(upload_to="invoices/")

    class Meta:
        verbose_name_plural = "6. Invoice"

    def __str__(self):
        return str(self.invoice_number)


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(status=0)
        # _________________________________________


class Product(models.Model):
    status_choice = (("0", "Available"), ("1", "Not Available"),)
    part_name = models.ForeignKey(Catelogue, related_name='catlogue_part_name', on_delete=models.CASCADE, null=True)
    # part_number = models.ForeignKey(Catelogue, related_name='catlogue_part_number', on_delete=models.CASCADE, null=True)
    # photo_display = models.ForeignKey(Catelogue, related_name='related_photo', on_delete=models.CASCADE, null=True)
    # reference for photo in html should be like below
    # src = "{{ product.photo_display.photo.url }}
    invoice_number = models.ForeignKey(Invoice, related_name='invoice', on_delete=models.CASCADE, null=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='product_added_by', on_delete=models.CASCADE, null=True)
    purchase_price = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    price = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    Quantity = models.IntegerField(default='0')
    max_discount = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=10, choices=status_choice, default='0')
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "7. Products"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:detail_product', args=[self.id])

    def __str__(self):
        return str(self.part_name)


"""class Vendor (models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    vendor_name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    account_no = models.CharField(max_length=255)
    pan_no = models.CharField(max_length=255)
    gst_no = models.CharField(max_length=255)
    cin_no = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=choices, default='1')


    class Meta:
        verbose_name_plural = "8. Vendor"

    def __str__(self):
        return str(self.vendor_name)"""

app/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Bikes, Product, Company
from .filter import ProductFilter




# Create your views here.
def all_products(request):
    products = Product.products.all()[:6]
    # products = Product.objects.filter(in_stock=True)  # in_stock set to true will filter products which are out of stock
    return render(request, 'store/home.html', {'products': products})



def total_products(request):
    products = Product.products.all()
    brand = request.GET.get('brand')
    if brand:
        # products = ProductFilter(request.GET, queryset=products).qs
        products = Product.products.filter(part_name=brand)
    # filtered = ProductFilter(request.GET, queryset=products)
    return render(request, 'store/products/products.html', {'products': products})


"""def product_detail(request, part_name):
    product = get_object_or_404(Product, part_name=part_name)
    return render(request, 'store/products/details.html', {'product': product})
"""


def detail_product(request, id):
    product = get_object_or_404(Product, id=id)
    return render(request, 'store/products/details.html', {'product': product})


def bikes_list(request, bike_slug):
    bikes = get_object_or_404(Bikes, slug=bike_slug)
    products = Product.objects.filter(bikes=bikes)
    return render(request, 'store/products/bikes.html', {'bikes': bikes, 'products': products})

app/templates/store/products/details.html
{% extends "store/layout.html" %}
{% load static %}
{% block title %}


{% endblock %}
{% block content %}

<!-- previou boottrap file -->
<link rel="stylesheet" href="{% static 'ecom/css/pev_bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'ecom/css/prev_style.css' %}">

<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-white">
                <img class="img-fluid mx-auto d-block" width="400px" alt="Responsive image" src="{{ product.part_name.photo.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <div class="col border-bottom">
                    <h1 class="mb-0 h4">{{ product.part_name }}</h1>
			<p> </p>
                    <div>
                        <div class="border">
                            <div class="col border-bottom">
                                <div class="row p-3">
                                    <div class="col-6 h4">Product:-<strong>{{product.part_name}}</strong></div>
                                    <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }} &#8377</span></div>
                                </div>
                            </div>
				<div class="mt-4">
					<p>{{product.part_name.item_Description}}</p>
				</div>
					
                            <div class="col">
                                <div class="row p-3">
                                    <div class="qty mt-5" style="width: 31%">
                                        <span id="minus" class="minus bg-black">-</span>
                                        <input type="number" class="count" name="qty" value="1">
                                        <span id="plus" class="plus bg-black">+</span>
                                    </div>
                                    <div class="qty mt-5" style="width: 31%">
                                        <button type="button" id="add-button" value="{{product.id}}" class="btn btn-primary btn-sm">Add to basket
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('.count').val(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) { }
        });
    })
    $('.btn-number').click(function (e) {
        e.preventDefault();

        fieldName = $(this).attr('data-field');
        type = $(this).attr('data-type');
        var input = $("input[name='" + fieldName + "']");
        var currentVal = parseInt(input.val());
        if (!isNaN(currentVal)) {
            if (type == 'minus') {

                if (currentVal > input.attr('min')) {
                    input.val(currentVal - 1).change();
                }
                if (parseInt(input.val()) == input.attr('min')) {
                    $(this).attr('disabled', true);
                }

            } else if (type == 'plus') {

                if (currentVal < input.attr('max')) {
                    input.val(currentVal + 1).change();
                }
                if (parseInt(input.val()) == input.attr('max')) {
                    $(this).attr('disabled', true);
                }

            }
        } else {
            input.val(0);
        }
    });
    $('.input-number').focusin(function () {
        $(this).data('oldValue', $(this).val());
    });
    $('.input-number').change(function () {

        minValue = parseInt($(this).attr('min'));
        maxValue = parseInt($(this).attr('max'));
        valueCurrent = parseInt($(this).val());

        name = $(this).attr('name');
        if (valueCurrent >= minValue) {
            $(".btn-number[data-type='minus'][data-field='" + name + "']").removeAttr('disabled')
        } else {
            alert('Sorry, the minimum value was reached');
            $(this).val($(this).data('oldValue'));
        }
        if (valueCurrent <= maxValue) {
            $(".btn-number[data-type='plus'][data-field='" + name + "']").removeAttr('disabled')
        } else {
            alert('Sorry, the maximum value was reached');
            $(this).val($(this).data('oldValue'));
        }


    });
    $('.btn-number').click(function (e) {
        e.preventDefault();

        fieldName = $(this).attr('data-field');
        type = $(this).attr('data-type');
        var input = $("input[name='" + fieldName + "']");
        var currentVal = parseInt(input.val());
        if (!isNaN(currentVal)) {
            if (type == 'minus') {

                if (currentVal > input.attr('min')) {
                    input.val(currentVal - 1).change();
                }
                if (parseInt(input.val()) == input.attr('min')) {
                    $(this).attr('disabled', true);
                }

            } else if (type == 'plus') {

                if (currentVal < input.attr('max')) {
                    input.val(currentVal + 1).change();
                }
                if (parseInt(input.val()) == input.attr('max')) {
                    $(this).attr('disabled', true);
                }

            }
        } else {
            input.val(0);
        }
    });
    $('.input-number').focusin(function () {
        $(this).data('oldValue', $(this).val());
    });
    $('.input-number').change(function () {

        minValue = parseInt($(this).attr('min'));
        maxValue = parseInt($(this).attr('max'));
        valueCurrent = parseInt($(this).val());

        name = $(this).attr('name');
        if (valueCurrent >= minValue) {
            $(".btn-number[data-type='minus'][data-field='" + name + "']").removeAttr('disabled')
        } else {
            alert('Sorry, the minimum value was reached');
            $(this).val($(this).data('oldValue'));
        }
        if (valueCurrent <= maxValue) {
            $(".btn-number[data-type='plus'][data-field='" + name + "']").removeAttr('disabled')
        } else {
            alert('Sorry, the maximum value was reached');
            $(this).val($(this).data('oldValue'));
        }


    });
    $(".input-number").keydown(function (e) {
        // Allow: backspace, delete, tab, escape, enter and .
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 190]) !== -1 ||
            // Allow: Ctrl+A
            (e.keyCode == 65 && e.ctrlKey === true) ||
            // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
            // let it happen, don't do anything
            return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });




</script>

<script>
    $(document).ready(function () {
        $('.count').prop('disabled', true);
        $(document).on('click', '#plus', function () {
            $('.count').val(parseInt($('.count').val()) + 1);
        });
        $(document).on('click', '#minus', function () {
            $('.count').val(parseInt($('.count').val()) - 1);
            if ($('.count').val() == 0) {
                $('.count').val(1);
            }
        });
    });


</script>

{% endblock %}

app/templates/store/products/products.html
{% extends "store/layout.html" %}
{% load static %}
{% block title %}Products{% endblock %}
{% block content %}

<form method="get">
  {% csrf_token%}
  <input name="brand", Placeholder="Enter Brand Name">
  <button type="submit">Filter</button>
</form> 

<!-- product section -->
<section class="product_section layout_padding">
  <div class="container">
    <div class="heading_container heading_center">
      <h2>
        Our <span>products</span>
      </h2>
    </div>
    <div class="row">
      {% for product in products %}
      <div class="col-sm-6 col-md-4 col-lg-4">
        <a href="{{ product.get_absolute_url }}" class="stretched-link">
          <div class="box">
            <div class="img-box">
              <img src="{{ product.part_name.photo.url }}" alt="">
            </div>
            <div class="detail-box">
              <h5>
                {{ product.part_name }}
              </h5>
              <h6>
                {{product.price }}
              </h6>
              <p class="card-text">{{product.part_name.item_Description}}</p>
            </div>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="btn-box">
    <a href="">
      View All products
    </a>
  </div>
  </div>
</section>
<!-- end product section -->

<!--footer section -->

<footer class="footer_section">
  <div class="container">
    <div class="row">
      <div class="col-md-4 footer-col">
        <div class="footer_contact">
          <h4> Reach at.. </h4>
          <div class="contact_link_box">
            <a href=""> 
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Location
              </span>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Call +01 1234567890
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                demo@gmail.com
              </span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-4 footer-col">
        <div class="footer_detail">
          <a href="index.html" class="footer-logo">
            Famms
          </a>
          <p>
            Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin
            words, combined with
          </p>
          <div class="footer_social">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-pinterest" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="col-md-4 footer-col">
        <div class="map_container">
          <div class="map">
            <div id="googleMap"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-info">
      <div class="col-lg-7 mx-auto px-0">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a>
        </p>
      </div>
    </div>
  </div>
</footer>
<!-- footer section -->
<!-- jQery -->
<script src="js/jquery-3.4.1.min.js"></script>
<!-- popper js -->
<script src="js/popper.min.js"></script>
<!-- bootstrap js -->
<script src="js/bootstrap.js"></script>
<!-- custom js -->
<script src="js/custom.js"></script>

<!-- end footer section -->

{% endblock %}