app/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='store/account/registration/login.html',form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='store/account/registration/login.html'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),

    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="store/account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='store/account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='store/account/user/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="store/account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="store/account/user/reset_status.html"), name='password_reset_complete'),


    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="store/account/user/delete_confirm.html"),
         name='delete_confirmation'),
    path('profile/delete/', views.delete, name='delete'),
]

app/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

app/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('products/', views.total_products, name='total_products'),
    path('item/<id>/', views.detail_product, name='detail_product'),
    path('item/<slug:bike_slug>/', views.detail_product, name='bikes_list'),
]

app/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
from django.urls import reverse


class Company(models.Model):
    company_name = models.CharField(max_length=255, db_index=True)
    company_slug = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "1. Companies"

    def __str__(self):
        return self.company_name


class Bikes(models.Model):
    bike_name = models.CharField(max_length=255, db_index=True, null=True)
    bike_slug = models.SlugField(max_length=255, unique=True, null=True)
    company_name = models.ForeignKey(Company, related_name='company', on_delete=models.CASCADE, null=True)
    status = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "2. Bikes"
        ordering = ('-created',)

    def __str__(self):
        return self.bike_name


class Manufacturer(models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    manufacturer_name = models.CharField(max_length=255, db_index=True, null=True)
    manufacturer_slug = models.SlugField(max_length=255, unique=True, null=True)
    status = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "3. Manufacturer"
        ordering = ('-created',)

    def __str__(self):
        return self.manufacturer_name


class Supplier(models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    supplier_name = models.CharField(max_length=255, help_text='supplier Name')
    supplier_slug = models.SlugField(max_length=255, unique=True, null=True)
    manufacturer_name = models.ForeignKey(Manufacturer, related_name='manufacturer', on_delete=models.CASCADE,
                                          null=True)
    account_no = models.CharField(max_length=255,null=True,blank=True)
    pan_no = models.CharField(max_length=255,null=True,blank=True)
    gst_no = models.CharField(max_length=255,null=True,blank=True)
    cin_no = models.CharField(max_length=255,null=True,blank=True)
    status = models.CharField(max_length=10, choices=choices, default='1')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "4. Supplier"
        ordering = ('-created',)

    def __str__(self):
        return self.supplier_name


class Catelogue(models.Model):
    part_name = models.CharField(max_length=255)
    part_slug = models.SlugField(max_length=255, unique=True, null=True)
    part_number = models.CharField(max_length=255)
    part_for_bike = models.ForeignKey(Bikes, related_name='bike', on_delete=models.CASCADE, null=True)
    part_manufacturer = models.ForeignKey(Manufacturer, related_name='product_manufacturer', on_delete=models.CASCADE,
                                          null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)
    item_Description = models.TextField(blank=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='catlogue_added_by', on_delete=models.CASCADE, null=True)
    photo = models.ImageField(blank=True, upload_to="product_images/")  # storing links in database
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "5. Catelogue"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.part_slug])

    def __str__(self):
        return str(self.part_name)


class Invoice(models.Model):
    invoice_number = models.CharField(max_length=255)
    invoice_date = models.DateField()
    file = models.FileField(upload_to="invoices/")

    class Meta:
        verbose_name_plural = "6. Invoice"

    def __str__(self):
        return str(self.invoice_number)


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(status=0)
        # _________________________________________


class Product(models.Model):
    status_choice = (("0", "Available"), ("1", "Not Available"),)
    part_name = models.ForeignKey(Catelogue, related_name='catlogue_part_name', on_delete=models.CASCADE, null=True)
    # part_number = models.ForeignKey(Catelogue, related_name='catlogue_part_number', on_delete=models.CASCADE, null=True)
    # photo_display = models.ForeignKey(Catelogue, related_name='related_photo', on_delete=models.CASCADE, null=True)
    # reference for photo in html should be like below
    # src = "{{ product.photo_display.photo.url }}
    invoice_number = models.ForeignKey(Invoice, related_name='invoice', on_delete=models.CASCADE, null=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='product_added_by', on_delete=models.CASCADE, null=True)
    purchase_price = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    price = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    Quantity = models.IntegerField(default='0')
    max_discount = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=10, choices=status_choice, default='0')
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "7. Products"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:detail_product', args=[self.id])

    def __str__(self):
        return str(self.part_name)


"""class Vendor (models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    vendor_name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    account_no = models.CharField(max_length=255)
    pan_no = models.CharField(max_length=255)
    gst_no = models.CharField(max_length=255)
    cin_no = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=choices, default='1')


    class Meta:
        verbose_name_plural = "8. Vendor"

    def __str__(self):
        return str(self.vendor_name)"""

app/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Bikes, Product, Company
from .filter import ProductFilter




# Create your views here.
def all_products(request):
    products = Product.products.all()[:6]
    # products = Product.objects.filter(in_stock=True)  # in_stock set to true will filter products which are out of stock
    return render(request, 'store/home.html', {'products': products})



def total_products(request):
    products = Product.products.all()
    brand = request.GET.get('brand')
    if brand:
        # products = ProductFilter(request.GET, queryset=products).qs
        products = Product.products.filter(part_name=brand)
    # filtered = ProductFilter(request.GET, queryset=products)
    return render(request, 'store/products/products.html', {'products': products})


"""def product_detail(request, part_name):
    product = get_object_or_404(Product, part_name=part_name)
    return render(request, 'store/products/details.html', {'product': product})
"""


def detail_product(request, id):
    product = get_object_or_404(Product, id=id)
    return render(request, 'store/products/details.html', {'product': product})


def bikes_list(request, bike_slug):
    bikes = get_object_or_404(Bikes, slug=bike_slug)
    products = Product.objects.filter(bikes=bikes)
    return render(request, 'store/products/bikes.html', {'bikes': bikes, 'products': products})

app/templates/store/layout.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
   <!-- Basic -->
   <meta charset="utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge" />
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
   <!-- Site Metas -->
   <meta name="keywords" content="" />
   <meta name="description" content="" />
   <meta name="author" content="" />
   <link rel="shortcut icon" href="/static/Mymotokart.png" type="">
   <title>{% block title %}MOTOCROSS{% endblock %}</title>
   <!-- bootstrap core css -->
   <link rel="stylesheet" type="text/css" href="{% static 'ecom/css/bootstrap.css' %}" />
   <!-- font awesome style -->
   <link href="{% static 'ecom/css/font-awesome.min.css' %}" rel="stylesheet" />
   <!-- Custom styles for this template -->
   <link href="{% static 'ecom/css/style.css' %}" rel="stylesheet" />
   <!-- responsive style -->
   <link href="{% static 'ecom/css/responsive.css' %}" rel="stylesheet" />

   <link rel="stylesheet" href="{% static 'ecom/css/base.css' %}">

   <script src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"></script>

   <!-- previou boottrap file -->
   <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"> -->
   <!-- <link rel="stylesheet" href="{% static 'ecom/css/pev_bootstrap.css' %}"> -->


</head>

<!-- header section strats -->
<header class="header_section" style="background-color: #e3e1e1;">
   <div class="container">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
         <a class="navbar-brand" href="/"><img width="250" src="/static/Mymotokart.png" alt="#" /></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
         </button>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
               <li class="nav-item active">
                  <a class="nav-link" href="/">Home </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="/products">Products</a>
               </li>

               <!--  Admin Option -->
               {% if user.is_superuser %}
               <li class="nav-item">
                  <a class="nav-link" href="/admin">admin</a>
               </li>
               {% endif %}
               <!-- ------------- -->

               <!-- <li class="nav-item">
                  <a class="nav-link" href="contact.html">Contact</a>
               </li> -->

               <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true"
                     aria-expanded="true"> <span class="nav-label">Account<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                     <li><a href="/account/dashboard">Orders</a></li>
                     {% if user.is_authenticated %}
                     <li><a href="{% url 'account:logout' %}">Logout</a></li>
                     {% else %}
                     <li><a href="{% url 'account:login' %}">Login</a></li>
                     {% endif %}
                  </ul>
               </li>

               <li class="nav-item">
                  <a class="nav-link" href="{% url 'payment:basket' %}">
                     {% with total_qty=basket|length %}
                     <div id="basket-qty" class="d-inline-flex basket-qty">
                        {% if total_qty > 0 %}
                        {{ total_qty }}
                        {% else %}

                        {% endif %}
                     </div>
                     {% endwith %}
                     <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                        xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029"
                        style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                        <g>
                           <g>
                              <path
                                 d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                                  c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                           </g>
                        </g>
                        <g>
                           <g>
                              <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                                  C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                                  c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                                  C457.728,97.71,450.56,86.958,439.296,84.91z" />
                           </g>
                        </g>
                        <g>
                           <g>
                              <path
                                 d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                                  c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                           </g>
                        </g>
                     </svg>
                  </a>
               </li>
            </ul>
         </div>
      </nav>
   </div>
</header>
<!-- end header section -->


<div id="content">{% block content %} {% endblock %}</div>


<!-- jQery -->
<script src=""></script>
<!-- popper js -->
<script src="/static/ecom/js/jquery-3.4.1.min.js"></script>
<!-- bootstrap js -->
<script src="/static/ecom/js/bootstrap.js"></script>
<!-- custom js -->
<script src="/static/ecom/js/custom.js"></script>
</body>

</html>