app/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='store/account/registration/login.html',form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='store/account/registration/login.html'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),

    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="store/account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='store/account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='store/account/user/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="store/account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="store/account/user/reset_status.html"), name='password_reset_complete'),


    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="store/account/user/delete_confirm.html"),
         name='delete_confirmation'),
    path('profile/delete/', views.delete, name='delete'),
]

app/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from django.core.mail import send_mail


# Create your models here.
class CustomAccountManager(BaseUserManager):
    def create_superuser(self, email, user_name, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)
        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff=True')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must be assigned to is_superuser=True')
        return self.create_user(email, user_name, password, **other_fields)

    def create_user(self, email, user_name, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))
        email = self.normalize_email(email)
        user = self.model(email=email, user_name=user_name, **other_fields)
        user.set_password(password)
        user.save()
        return user


class UserBase(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    user_name = models.CharField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255)

    # Adress Data
    phone_number = models.CharField(max_length=12)
    Address = models.TextField(max_length=500, blank=True)
    city = models.CharField(max_length=255)
    pincode = models.CharField(max_length=255)

    # user status
    # status = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False, verbose_name='status')
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name']

    class Meta:
        verbose_name_plural = "1. Accounts"

    def email_user(self, subject, message):
        send_mail(
            subject,
            message,
            'motokart@motocrossindia.in',
            [self.email],
            fail_silently=False,
        )

    def __str__(self):
        return self.user_name

app/account/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm, AuthenticationForm

from .models import UserBase


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Email address',
            'id': 'login-username'
        }
    )
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'id': 'login-pwd',
        }
    )
    )


class RegistrationForm(forms.ModelForm):
    user_name = forms.CharField(
        label='Enter Username',
        min_length=4,
        max_length=50,
        help_text='Required'
    )
    email = forms.EmailField(
        max_length=100,
        help_text='Required',
        error_messages={'required': 'Sorry, you will need an email'}
    )
    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Repeat password',
        widget=forms.PasswordInput
    )

    class Meta:
        model = UserBase
        fields = ('user_name', 'email')

    def clean_user_name(self):
        user_name = self.cleaned_data['user_name'].lower()
        r = UserBase.objects.filter(user_name=user_name)
        if r.count():
            raise forms.ValidationError("Username already exists")
        return user_name

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if UserBase.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Please use another Email, that is already taken')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'E-mail', 'name': 'email', 'id': 'id_email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'})


class PwdResetForm(PasswordResetForm):
    email = forms.EmailField(
        max_length=254,
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Email',
            'id': 'form-email'
        }
        )
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        usr = UserBase.objects.filter(email=email)
        if not usr:
            raise forms.ValidationError(
                'Unfortunatley we can not find that email address')
        return email


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserEditForm(forms.ModelForm):
    email = forms.EmailField(label='Account Email (can not be changed)',
                             max_length=200,
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control mb-3',
                                        'placeholder': 'email',
                                        'id': 'form-email',
                                        'readonly': 'readonly'})
                             )

    user_name = forms.CharField(label='User Name',
                                max_length=255,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control mb-3',
                                           'placeholder': 'Username',
                                           'id': 'form-user_name',
                                           'readonly': 'readonly'})
                                )

    first_name = forms.CharField(label='Full Name',
                                 max_length=255,
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control mb-3',
                                            'placeholder': 'Full Name',
                                            'id': 'form-fullname'})
                                 )

    phone_number = forms.CharField(label='Phone Number',
                                   max_length=12,
                                   widget=forms.TextInput(
                                       attrs={'class': 'form-control mb-3',
                                              'placeholder': 'Phone Number',
                                              'id': 'form-phonenumber'})
                                   )
    Address = forms.CharField(label='Address',
                           max_length=255,
                           widget=forms.TextInput(
                               attrs={'class': 'form-control mb-3',
                                      'placeholder': 'Address',
                                      'id': 'form-address'})
                           )

    city = forms.CharField(label='city',
                           max_length=255,
                           widget=forms.TextInput(
                               attrs={'class': 'form-control mb-3',
                                      'placeholder': 'city',
                                      'id': 'form-city'})
                           )

    pincode = forms.CharField(label='pin',
                              max_length=255,
                              widget=forms.TextInput(
                                  attrs={'class': 'form-control mb-3',
                                         'placeholder': 'pin',
                                         'id': 'form-pin'})
                              )


    class Meta:
        model = UserBase
        fields = ('email', 'user_name', 'first_name','phone_number','city','pincode','Address')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].required = True
        self.fields['email'].required = True

app/account/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from orders.views import user_orders
from .forms import RegistrationForm, UserEditForm
from django.contrib.sites.shortcuts import get_current_site

from .models import UserBase
from .tokens import account_activation_token


@login_required
def dashboard(request):
    orders = user_orders(request)
    return render(request,
                  'store/account/user/dashboard.html',
                  {'section': 'profile', 'orders': orders})
    # return render(request, 'store/account/user/dashboard.html')


@login_required
def edit_details(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        """email = request.POST.get("email", '')
        city = request.POST.get("city", '')
        pincode = request.POST.get("pincode", '')
        address = request.POST.get("Address", '')
        # UserBase.objects.filter(email=email).update(city=city, pincode=pincode, Address=address)"""
        user_form.save()
        if user_form.is_valid():
            user_form.save()

    else:
        user_form = UserEditForm(instance=request.user)

    return render(request, 'store/account/user/edit_details.html', {'user_form': user_form})


@login_required
def delete_user(request):
    user = UserBase.objects.get(user_name=request.user)
    user.is_active = False
    user.save()
    logout(request)
    return redirect('account:delete_confirmation')

def delete(request):
    return render(request, 'store/account/user/delete.html')


def account_register(request):
    """if request.user.is_authenticated:
        return redirect('account:dashboard')"""

    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            user.email = registerForm.cleaned_data['email']
            user.set_password(registerForm.cleaned_data['password'])
            user.status = False
            user.save()
            current_site = get_current_site(request)
            new_token = account_activation_token.make_token(user)
            subject = 'Activate your Account'
            message = render_to_string('store/account/registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': new_token,
            })
            user.email_user(subject=subject, message=message)
            return render(request,'store/account/registration/account_successfull.html',{'form':registerForm})
    else:
        registerForm = RegistrationForm()
    return render(request, 'store/account/registration/register.html', {'form': registerForm})


def account_activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = UserBase.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError, user.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('account:dashboard')
    else:
        return render(request, 'store/account/registration/activation_invalid.html')

app/templates/store/account/user/dashboard.html
{% extends "../../layout.html" %} 
{% load static %} 
{% block title %}Basket Summary{%endblock %} 
{% block content %}

<main class="pt-5">
    <div class="container" style="max-width: 1000px">
        <div class="col-12">
            <h1 class="h2">Your Orders</h1>
        </div>
        <div class="col-12 d-flex justify-content-between">
            <div>Manage your <b>orders</b> and personal details</div>
            <div class="col-3 d-flex justify-content-between">
                <div><a href="{% url 'account:edit_details' %}">Change Account Details</a></div>
                <div><a href="/"> Home </a></div>
            </div>
        </div>
        <hr />
    </div>
    <div class="container " style="max-width: 1000px">
        {% for order in orders %}
        <div class="row g-3">
            <div class="col-12 bg-warning p-3 d-flex justify-content-between">
                <div class="d-flex d-flex-inline">

                    <div class="pe-3">{{ order.created }}</div>

                </div>
                <div class="text-end">
                    Total paid: <span class="fw-bold text-danger">{{ order.total_amount }} &#8377</span>
                </div>
            </div>
            <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
                <div class="d-grid gap-2 ">
                    <!--          <button class="btn btn-warning" type="button">Problem with order</button>-->
                    <button class="btn btn-light disabled" type="button">Review Your Order</button>
                </div>
            </div>
            <div class="col-md-7 col-lg-8 p-0">

                {% for item in order.items.all %}

                <div class="card mb-3 border-0">
                    <div class="row g-0">
                        <div class="col-md-2 d-none d-md-block">
                            <img class="img-fluid" style="width:90px" src="{{item.product.part_name.photo.url}}" />
                        </div>
                        <div class="col-md-10 d-none d-md-block">
                            <div class="card-body p-1">
                                <a class="text-decoration-none" href="{{ item.product.get_absolute_url }}">
                                    <p class="card-text small">{{item.product|title}}</p>
                                </a>
                            </div>
                            <div class="card-body p-1">
                                <a class="text-decoration-none" href="{{ item.product.get_absolute_url }}">
                                    <p class="card-text small">{{item.product.price}} &#8377</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</main>


{% endblock %}

app/templates/store/account/user/delete.html
{% extends "../../layout.html" %}
{% block title %}Delete account{% endblock %}
{% block content %}


<form class="account-form px-4" action="{% url 'account:delete_user' %}" method="post">
    {% csrf_token %}
    <p class=" h3 pt-4 font-weight-bold">Delete Account</p>
    <p>Are you sure you want to delete your account?</p>
    <button type="submit" role="button"
            class="btn btn-danger">Delete
    </button>
</form>


{% endblock %}

app/templates/store/account/user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The Motocross team{% endblocktranslate %}

{% endautoescape %}

app/templates/store/account/user/password_reset_form.html
{% comment %} {% extends "../../layout.html" %}
{% block title %}Password Reset{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<script>
    window.location.href = '{% url "account:dashboard" %}';
</script>
{% endif %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">
                            <form class="account-form p-4 rounded col-lg-8 mx-auto" method="post"
                                action="{% url 'account:pwdreset' %}">
                                <p class="h3 mb-4 font-weight-bold">Forgotten your password?</p>
                                <p>Enter your e-mail address to obtain a new password.</p>
                                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Error: Please try again!
                                </div>
                                {% endif %}
                                {% csrf_token %}
                                <label class="small font-weight-bold">{{ form.email.label}}</label>
                                {{ form.email }}
                                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
                                    value="Send e-mail">Send e-mail</button>
                                <p class="text-center"><a href="{% url 'account:login' %}">Login</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% endcomment %}
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8" />
    <title>{% block title %}MOTOCROSS{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }

        html {
            background: url(/static/bg0.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        html,
        body {
            display: grid;
            height: 100%;
            width: 100%;
            place-items: center;
            /* background: url(/static/motocross-india-logo.png) no-repeat center center fixed;
        width:100%;
        height: 100%;
        padding:0px;
        margin:0px; */

        }

        body {
            background: url(/static/bg0.jpg) no-repeat center center fixed;
            background-size: cover;
        }

        ::selection {
            background: orange;
            color: #fff;
        }

        .wrapper {
            overflow: hidden;
            max-width: 390px;
            background: #fff;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0px 15px 20px rgba(0, 0, 0, 0.1);
            opacity: 0.9;
        }

        .wrapper .title-text {
            display: flex;
            width: 200%;
        }

        .wrapper .title {
            width: 50%;
            font-size: 35px;
            font-weight: 600;
            text-align: center;
            transition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
        }

        .wrapper .slide-controls {
            position: relative;
            display: flex;
            height: 50px;
            width: 100%;
            overflow: hidden;
            margin: 30px 0 10px 0;
            justify-content: space-between;
            border: 1px solid lightgrey;
            border-radius: 5px;
        }

        .slide-controls .slide {
            height: 100%;
            width: 100%;
            color: #fff;
            font-size: 18px;
            font-weight: 500;
            text-align: center;
            line-height: 48px;
            cursor: pointer;
            z-index: 1;
            transition: all 0.6s ease;
        }

        .slide-controls label.signup {
            color: #000;
        }

        .slide-controls .slider-tab {
            position: absolute;
            height: 100%;
            width: 50%;
            left: 0;
            z-index: 0;
            border-radius: 5px;
            background: -webkit-linear-gradient(left, rgb(255, 136, 0), rgb(241, 118, 47));
            transition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
        }

        input[type="radio"] {
            display: none;
        }

        #signup:checked~.slider-tab {
            left: 50%;
        }

        #signup:checked~label.signup {
            color: #fff;
            cursor: default;
            user-select: none;
        }

        #signup:checked~label.login {
            color: #000;
        }

        #login:checked~label.signup {
            color: #000;
        }

        #login:checked~label.login {
            cursor: default;
            user-select: none;
        }

        .wrapper .form-container {
            width: 100%;
            overflow: hidden;
        }

        .form-container .form-inner {
            display: flex;
            width: 200%;
        }

        .form-container .form-inner form {
            width: 50%;
            transition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
        }

        .form-inner form .field {
            height: 50px;
            width: 100%;
            margin-top: 20px;
        }

        .form-inner form .field input {
            height: 100%;
            width: 100%;
            outline: none;
            padding-left: 15px;
            border-radius: 5px;
            border: 1px solid lightgrey;
            border-bottom-width: 2px;
            font-size: 17px;
            transition: all 0.3s ease;
        }

        .form-inner form .field input:focus {
            border-color: rgb(248, 182, 59);
            /* box-shadow: inset 0 0 3px #fb6aae; */
        }

        .form-inner form .field input::placeholder {
            color: #999;
            transition: all 0.3s ease;
        }

        form .field input:focus::placeholder {
            color: #b3b3b3;
        }

        .form-inner form .pass-link {
            margin-top: 5px;
        }

        .form-inner form .signup-link {
            text-align: center;
            margin-top: 30px;
        }

        .form-inner form .pass-link a,
        .form-inner form .signup-link a {
            color: rgb(241, 191, 97);
            text-decoration: none;
        }

        .form-inner form .pass-link a:hover,
        .form-inner form .signup-link a:hover {
            text-decoration: underline;
        }

        form .btn {
            height: 50px;
            width: 100%;
            border-radius: 5px;
            position: relative;
            overflow: hidden;
        }

        form .btn .btn-layer {
            height: 100%;
            width: 300%;
            position: absolute;
            left: -100%;
            background: -webkit-linear-gradient(right, rgb(248, 182, 59), rgb(241, 191, 97), rgb(255, 136, 0), rgb(241, 118, 47));
            border-radius: 5px;
            transition: all 0.4s ease;
            ;
        }

        form .btn:hover .btn-layer {
            left: 0;
        }

        form .btn input[type="submit"] {
            height: 100%;
            width: 100%;
            z-index: 1;
            position: relative;
            background: none;
            border: none;
            color: #fff;
            padding-left: 0;
            border-radius: 5px;
            font-size: 20px;
            font-weight: 500;
            cursor: pointer;
        }

        .logo {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
        }
    </style>
</head>

<body>
    <div class="wrapper">
        <div class="log">
            <img src="/static/Mymotokart.png" alt="" class="center" width="40%" height="20%">
        </div>
        <div class="title-text">
            <div class="title login">
                Reset Password
            </div>
        </div>
        <div class="form-container">

        </div>
        <div class="form-inner">
            <form class="login account-form" action="{% url 'account:pwdreset' %}" method="post">
                {% csrf_token %}

                {% if form.errors %}



                <div class="alert alert-primary" role="alert">
                    Error: Username or Password not correct!
                </div>
                {% endif %}
                <label class="small font-weight-bold">{{ form.email.label}}</label>
                                {{ form.email }}

                <div class="field btn d-grid gap-2 py-2 mt-5">
                    <div class="btn-layer"></div>
                    <input type="submit" value="Reset">
                    <input type="hidden" name="next" value="{{ next }}">
                </div>
                <div class="signup-link">
                    Not a member? <a href="{% url 'account:register' %}">Signup now</a>
                    <div class="pass-link">
                        <a href="{% url 'account:pwdreset' %}">Forgot password?</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>