app/basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

app/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/payment/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name = 'payment'

urlpatterns = [
    path('basket/', views.basket, name='basket'),
    path('shipping/', views.shipping, name='shipping'),
    path('razorpay/', views.homepage, name='homepage'),
    path('razorpay/paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('admin/', admin.site.urls),
]

# path('', views.BasketView, name='basket'),
# path('pay/', views.initiate_payment, name='pay'),
# path('callback/', views.callback, name='callback'),
# path('razorpay/', views.homepage, name='index'),

app/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.all_products, name='all_products'),
    path('products/', views.total_products, name='total_products'),
    path('item/<id>/', views.detail_product, name='detail_product'),
    path('item/<slug:bike_slug>/', views.detail_product, name='bikes_list'),
]

app/payment/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Transaction(models.Model):
    made_by_user = models.ForeignKey(User, related_name='transactions', on_delete=models.CASCADE)
    date_of_transaction = models.DateTimeField(auto_now_add=True)
    amount_of_transaction = models.IntegerField()
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True)
    payment_id = models.CharField(max_length=100, null=True, blank=True)

    """def save(self, *args, **kwargs):
        if self.order_id is None and self.date_of_transaction and self.id:
            self.order_id = self.date_of_transaction.strftime('MOTOCROSS%Y%m%dODR') + str(self.id)
        return super().save(*args, **kwargs)"""

app/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
from django.urls import reverse


class Company(models.Model):
    company_name = models.CharField(max_length=255, db_index=True)
    company_slug = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "1. Companies"

    def __str__(self):
        return self.company_name


class Bikes(models.Model):
    bike_name = models.CharField(max_length=255, db_index=True, null=True)
    bike_slug = models.SlugField(max_length=255, unique=True, null=True)
    company_name = models.ForeignKey(Company, related_name='company', on_delete=models.CASCADE, null=True)
    status = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "2. Bikes"
        ordering = ('-created',)

    def __str__(self):
        return self.bike_name


class Manufacturer(models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    manufacturer_name = models.CharField(max_length=255, db_index=True, null=True)
    manufacturer_slug = models.SlugField(max_length=255, unique=True, null=True)
    status = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "3. Manufacturer"
        ordering = ('-created',)

    def __str__(self):
        return self.manufacturer_name


class Supplier(models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    supplier_name = models.CharField(max_length=255, help_text='supplier Name')
    supplier_slug = models.SlugField(max_length=255, unique=True, null=True)
    manufacturer_name = models.ForeignKey(Manufacturer, related_name='manufacturer', on_delete=models.CASCADE,
                                          null=True)
    account_no = models.CharField(max_length=255,null=True,blank=True)
    pan_no = models.CharField(max_length=255,null=True,blank=True)
    gst_no = models.CharField(max_length=255,null=True,blank=True)
    cin_no = models.CharField(max_length=255,null=True,blank=True)
    status = models.CharField(max_length=10, choices=choices, default='1')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "4. Supplier"
        ordering = ('-created',)

    def __str__(self):
        return self.supplier_name


class Catelogue(models.Model):
    part_name = models.CharField(max_length=255)
    part_slug = models.SlugField(max_length=255, unique=True, null=True)
    part_number = models.CharField(max_length=255)
    part_for_bike = models.ForeignKey(Bikes, related_name='bike', on_delete=models.CASCADE, null=True)
    part_manufacturer = models.ForeignKey(Manufacturer, related_name='product_manufacturer', on_delete=models.CASCADE,
                                          null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)
    item_Description = models.TextField(blank=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='catlogue_added_by', on_delete=models.CASCADE, null=True)
    photo = models.ImageField(blank=True, upload_to="product_images/")  # storing links in database
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "5. Catelogue"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.part_slug])

    def __str__(self):
        return str(self.part_name)


class Invoice(models.Model):
    invoice_number = models.CharField(max_length=255)
    invoice_date = models.DateField()
    file = models.FileField(upload_to="invoices/")

    class Meta:
        verbose_name_plural = "6. Invoice"

    def __str__(self):
        return str(self.invoice_number)


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(status=0)
        # _________________________________________


class Product(models.Model):
    status_choice = (("0", "Available"), ("1", "Not Available"),)
    part_name = models.ForeignKey(Catelogue, related_name='catlogue_part_name', on_delete=models.CASCADE, null=True)
    # part_number = models.ForeignKey(Catelogue, related_name='catlogue_part_number', on_delete=models.CASCADE, null=True)
    # photo_display = models.ForeignKey(Catelogue, related_name='related_photo', on_delete=models.CASCADE, null=True)
    # reference for photo in html should be like below
    # src = "{{ product.photo_display.photo.url }}
    invoice_number = models.ForeignKey(Invoice, related_name='invoice', on_delete=models.CASCADE, null=True)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='product_added_by', on_delete=models.CASCADE, null=True)
    purchase_price = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    price = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    Quantity = models.IntegerField(default='0')
    max_discount = models.DecimalField(decimal_places=2, max_digits=10, default='0')
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=10, choices=status_choice, default='0')
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = "7. Products"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:detail_product', args=[self.id])

    def __str__(self):
        return str(self.part_name)


"""class Vendor (models.Model):
    choices = (("0", "INACTIVE"), ("1", "ACTIVE"),)
    vendor_name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255)
    account_no = models.CharField(max_length=255)
    pan_no = models.CharField(max_length=255)
    gst_no = models.CharField(max_length=255)
    cin_no = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=choices, default='1')


    class Meta:
        verbose_name_plural = "8. Vendor"

    def __str__(self):
        return str(self.vendor_name)"""

app/payment/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from orders.views import add_order, payment_confirmation, billing_address
from basket.basket import Basket
import razorpay
from django.http import HttpResponseBadRequest

razorpay_client = razorpay.Client(auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))


def basket(request):
    return render(request, 'store/payment/summary.html')


def shipping(request):
    return render(request, 'store/payment/shipping.html')


@login_required
def homepage(request):
    currency = 'INR'
    basket = Basket(request)
    total = str(basket.get_total_price())
    total1 = total.replace('.', '')
    amount = int(total1)


    razorpay_order = razorpay_client.order.create(dict(amount=amount,
                                                       currency=currency,
                                                       payment_capture='0'))
    print(razorpay_order)


    razorpay_order_id = razorpay_order['id']
    razorpay_order_status = razorpay_order['status']
    callback_url = 'paymenthandler/'
    try:
        add_order(razorpay_order, request)
    except Exception as e:
        print(e)
    try:
        billing_address(request,razorpay_order['id'])
    except Exception as ex:
        print(ex)

    context = {'razorpay_order_id': razorpay_order_id,
               'razorpay_order_status': razorpay_order_status,
               'razorpay_merchant_key': settings.RAZOR_KEY_ID,
               'razorpay_amount': amount,
               'currency': currency,
               'callback_url': callback_url,
               'basket':basket,
               'amount': total,
               }
    return render(request, 'store/payment/final_pay.html', context=context)


@csrf_exempt
def success(request):
    return render(request, "success.html")


@csrf_exempt
def paymenthandler(request):
    check_basket = Basket(request)
    total = str(check_basket.get_total_price())
    total = total.replace('.', '')
    check_amount = int(total)

    if request.method == "POST":
        try:
            payment_id = request.POST.get('razorpay_payment_id', '')
            razorpay_order_id = request.POST.get('razorpay_order_id', '')
            signature = request.POST.get('razorpay_signature', '')
            params_dict = {
                'razorpay_order_id': razorpay_order_id,
                'razorpay_payment_id': payment_id,
                'razorpay_signature': signature,
            }

            result = razorpay_client.utility.verify_payment_signature(params_dict)
            if result is True:
                try:
                    razorpay_client.payment.capture(payment_id, check_amount)
                    # Save this order to database here note by onkar
                    payment_confirmation(razorpay_order_id, )
                    check_basket.clear()
                    return render(request, 'store/payment/payment_successfull.html')
                except:
                    return render(request, 'store/payment/payment_fail.html')
            else:
                return render(request, 'store/payment/payment_fail.html')
        except:
            return HttpResponseBadRequest()
    else:
        return HttpResponseBadRequest()

app/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Bikes, Product, Company
from .filter import ProductFilter




# Create your views here.
def all_products(request):
    products = Product.products.all()[:6]
    # products = Product.objects.filter(in_stock=True)  # in_stock set to true will filter products which are out of stock
    return render(request, 'store/home.html', {'products': products})



def total_products(request):
    products = Product.products.all()
    brand = request.GET.get('brand')
    if brand:
        # products = ProductFilter(request.GET, queryset=products).qs
        products = Product.products.filter(part_name=brand)
    # filtered = ProductFilter(request.GET, queryset=products)
    return render(request, 'store/products/products.html', {'products': products})


"""def product_detail(request, part_name):
    product = get_object_or_404(Product, part_name=part_name)
    return render(request, 'store/products/details.html', {'product': product})
"""


def detail_product(request, id):
    product = get_object_or_404(Product, id=id)
    return render(request, 'store/products/details.html', {'product': product})


def bikes_list(request, bike_slug):
    bikes = get_object_or_404(Bikes, slug=bike_slug)
    products = Product.objects.filter(bikes=bikes)
    return render(request, 'store/products/bikes.html', {'bikes': bikes, 'products': products})

app/templates/store/payment/payment_fail.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
	  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<style type="text/css">

    body
    {
        background:#f2f2f2;
    }

    .payment
	{
		border:1px solid #f2f2f2;
		height:280px;
        border-radius:20px;
        background:#fff;
	}
   .payment_header
   {
	   background:rgb(247, 10, 10);
	   padding:20px;
       border-radius:20px 20px 0px 0px;

   }

   .check
   {
	   margin:0px auto;
	   width:50px;
	   height:50px;
	   border-radius:100%;
	   background:#fff;
	   text-align:center;
   }

   .check i
   {
	   vertical-align:middle;
	   line-height:50px;
	   font-size:30px;
   }

    .content
    {
        text-align:center;
    }

    .content  h1
    {
        font-size:25px;
        padding-top:25px;
    }

    .content a
    {
        width:200px;
        height:35px;
        color:#fff;
        border-radius:30px;
        padding:5px 10px;
        background:rgb(247, 10, 10);
        transition:all ease-in-out 0.3s;
    }

    .content a:hover
    {
        text-decoration:none;
        background:#000;
    }

</style>
  </head>
  <body>
  <div class="container">
   <div class="row">
      <div class="col-md-6 mx-auto mt-5">
         <div class="payment">
            <div class="payment_header">
               <div class="check"><i class="fa fa-check" aria-hidden="true"></i></div>
            </div>
            <div class="content">
               <h1>Payment Fail!</h1>
                <p>Couldn't process your order. Payment has been failed.</p>
               <a href="/">Go to Home</a>
            </div>

         </div>
      </div>
   </div>
</div>
  </body>

app/templates/store/payment/shipping.html
{% load static %}
{% block title %}{% endblock %}
{% block content %}

<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
</script>
<style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Poppins', sans-serif;
    }

    html {
      background: url(/static/bg0.jpg) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }

    html,
    body {
      display: grid;
      height: 100%;
      width: 100%;
      place-items: center;
      /* background: url(/static/motocross-india-logo.png) no-repeat center center fixed;
  width:100%;
  height: 100%;
  padding:0px;
  margin:0px; */

    }
    body{
        background: url(/static/bg0.jpg) no-repeat center center fixed;
        background-size: cover;
    }

    ::selection {
      background: orange;
      color: #fff;
    }

    .container {
      overflow: hidden;
      max-width: 390px;
      background: #fff;
      padding: 30px;
      border-radius: 5px;
      box-shadow: 0px 15px 20px rgba(0, 0, 0, 0.1);
      opacity: 0.9;
    }

    .container .title-text {
      display: flex;
      width: 200%;
    }

    .container .title {
      width: 50%;
      font-size: 35px;
      font-weight: 600;
      text-align: center;
      transition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
    }

    .container .slide-controls {
      position: relative;
      display: flex;
      height: 50px;
      width: 100%;
      overflow: hidden;
      margin: 30px 0 10px 0;
      justify-content: space-between;
      border: 1px solid lightgrey;
      border-radius: 5px;
    }

    .slide-controls .slide {
      height: 100%;
      width: 100%;
      color: #fff;
      font-size: 18px;
      font-weight: 500;
      text-align: center;
      line-height: 48px;
      cursor: pointer;
      z-index: 1;
      transition: all 0.6s ease;
    }

    .slide-controls label.signup {
      color: #000;
    }

    .slide-controls .slider-tab {
      position: absolute;
      height: 100%;
      width: 50%;
      left: 0;
      z-index: 0;
      border-radius: 5px;
      background: -webkit-linear-gradient(left, rgb(255, 136, 0), rgb(241, 118, 47));
      transition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
    }

    input[type="radio"] {
      display: none;
    }

    #signup:checked~.slider-tab {
      left: 50%;
    }

    #signup:checked~label.signup {
      color: #fff;
      cursor: default;
      user-select: none;
    }

    #signup:checked~label.login {
      color: #000;
    }

    #login:checked~label.signup {
      color: #000;
    }

    #login:checked~label.login {
      cursor: default;
      user-select: none;
    }

    .container .form-container {
      width: 100%;
      overflow: hidden;
    }

    .form-container .form-inner {
      display: flex;
      width: 200%;
    }

    .form-container .form-inner form {
      width: 50%;
      transition: all 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
    }

    .form-inner form .field {
      height: 50px;
      width: 100%;
      margin-top: 20px;
    }

    .form-inner form .field input {
      height: 100%;
      width: 100%;
      outline: none;
      padding-left: 15px;
      border-radius: 5px;
      border: 1px solid lightgrey;
      border-bottom-width: 2px;
      font-size: 17px;
      transition: all 0.3s ease;
    }

    .form-inner form .field input:focus {
      border-color: rgb(248, 182, 59);
      /* box-shadow: inset 0 0 3px #fb6aae; */
    }

    .form-inner form .field input::placeholder {
      color: #999;
      transition: all 0.3s ease;
    }

    form .field input:focus::placeholder {
      color: #b3b3b3;
    }

    .form-inner form .pass-link {
      margin-top: 5px;
    }

    .form-inner form .signup-link {
      text-align: center;
      margin-top: 30px;
    }

    .form-inner form .pass-link a,
    .form-inner form .signup-link a {
      color: rgb(241, 191, 97);
      text-decoration: none;
    }

    .form-inner form .pass-link a:hover,
    .form-inner form .signup-link a:hover {
      text-decoration: underline;
    }

    form .btn {
      height: 50px;
      width: 100%;
      border-radius: 5px;
      position: relative;
      overflow: hidden;
    }

    form .btn .btn-layer {
      height: 100%;
      width: 300%;
      position: absolute;
      left: -100%;
      background: -webkit-linear-gradient(right, rgb(248, 182, 59), rgb(241, 191, 97), rgb(255, 136, 0), rgb(241, 118, 47));
      border-radius: 5px;
      transition: all 0.4s ease;
      ;
    }

    form .btn:hover .btn-layer {
      left: 0;
    }

    form .btn input[type="submit"] {
      height: 100%;
      width: 100%;
      z-index: 1;
      position: relative;
      background: none;
      border: none;
      color: #fff;
      padding-left: 0;
      border-radius: 5px;
      font-size: 20px;
      font-weight: 500;
      cursor: pointer;
    }

    .logo {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 20%;
    }

    .center {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 50%;
    }







</style>

<div class="container">
    <!--    <div class="log">-->
    <!--        <img src="/static/motocross-india-logo.png" alt="" class="center" width="40%" height="20%">-->
    <!--    </div>-->
    <div class="title-text">
        <div class="title login">
            Billing Address
            <form id="address_form" action="{% url 'payment:homepage' %}" method="POST">
                {% csrf_token %}
        </div>
    </div>
    <div class="row g-2">
        <div class="field py-2 mt-4">
            <label for="firstName" class="form-label">Customer Name</label>
            <input type="text" class="form-control" id="custName" placeholder="" required>
            <div class="invalid-feedback">
                Valid first name is required.
            </div>
            <div class="field py-2 mt-4">
                <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
                <input type="email" class="form-control" id="email" placeholder="you@example.com">
                <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                </div>
                <div class="field py-2 mt-4">
                    <label for="phone" class="form-label">Phone Number <span class="text-muted"></span></label>
                    <input type="phone" class="form-control" id="phone" placeholder="Number">
                    <div class="invalid-feedback">
                        Please enter Phone Number.
                    </div>
                    <div class="field py-2 mt-4">
                        <label for="firstName" class="form-label">Address</label>
                        <label for="custAdd" class="form-label">Address</label>
                        <textarea type="text" class="form-control" id="custAdd" placeholder="1234 Main St"
                                  required></textarea>
                        <div class="invalid-feedback">
                            Please enter your shipping address.
                        </div>

                    </div>
                </div>
                <button id="submit" class="btn btn-outline-success text-align: center"
                        data-secret="{{ client_secret }}">
                    Continue
                </button>
                </form>
            </div>
        </div>
    </div>

    <script>
    {% comment %} Make csrf token availble in JS files {% endcomment %}
    var CSRF_TOKEN = '{{ csrf_token }}';




    </script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'payment/index.js' %}" data-rel-js></script>
    <script>
    var options = {
        key: "{{ razorpay_merchant_key }}",
        amount: "{{ razorpay_amount }}",
        currency: "INR",
        name: "MOTOCROSS",
        order_id: "{{ razorpay_order_id }}",
        callback_url: "{{ callback_url }}",
    };

    var rzp1 = new Razorpay(options);

    document.getElementById("pay-btn").onclick = function (e) {
        rzp1.open();
        e.preventDefault();
    };




    </script>

    {% endblock %}

app/templates/store/payment/summary.html
{% extends "../layout.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

<!-- previou boottrap file -->
<link rel="stylesheet" href="{% static 'ecom/css/pev_bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'ecom/css/pev_style.css' %}">

<main class="pt-5">
    <div class="container">
        <h2 class="h2">Shopping basket</h2>
        {% for item in basket %}
        {% with product=item.product %}
        <div class="container">
        <main class="pt-1">
        <div data-index="{{product.id}}" class="row mb-4 border product-item">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first bg-white">
                    <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"
                        src="{{ product.part_name.photo.url }}">
                </div>
                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <div class="col border-bottom">
                        <h1 class="mb-0 h1">{{ product.part_name }}</h1>
                        <div>

                            <div class="border">
                                <div class="col border-bottom">
                                    <div class="row p-3">
                                        <div class="col-6">Product</div>
                                        <div class="col-6 text-end"><span class="h6 fw-bold">{{ product.price }}
                                                &#8377</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="row p-3">
                                        <div class="col-12">
                                            <label for="select{{product.id}}">Qty</label>
                                            <select id="select{{product.id}}">
                                                <option selected>
                                                    {{item.qty}}
                                                </option>
                                                <option value="">1</option>
                                                <option value="">2</option>
                                                <option value="">3</option>
                                                <option value="">4</option>
                                                <option value="">5</option>
                                                <option value="">6</option>
                                                <option value="">7</option>
                                                <option value="">8</option>
                                                <option value="">9</option>
                                                <option value="">10</option>

                                            </select>
                                            <button type="button" id="update-button" data-index="{{product.id}}"
                                                class="btn btn-outline-primary btn-sm update-button">
                                                Update
                                            </button>
                                            <button type="button" id="delete-button" data-index="{{product.id}}"
                                                class="btn btn-outline-danger btn-sm delete-button">
                                                Delete
                                            </button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </main>
        </div>

        {% endwith %}
        {% endfor %}
        <div class="col-12 text-end">
            <div class="h6 fw-bold">Sub Total:
                <div id="subtotal" class="d-inline-flex">{{basket.get_total_price}} &#8377</div>

            </div>

            </br>
            <!--            <div class="btn btn-outline-success" >Check Out</div>-->
            {% if basket.get_total_price > 0 %}
            <a type="button" role="button" href="{% url 'payment:shipping' %}"
                class="btn btn-outline-success mb-5">Check Out</a>
            {% else %}
            <a type="button" role="button" href="" class="btn btn-outline-secondary disabled mb-5">Check Out</a>
            {% endif %}
        </div>
    </div>
</main>

<script>
    // Delete Item
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                $('.product-item[data-index="' + prodid + '"]').remove();
                document.getElementById("subtotal").innerHTML = json.subtotal;
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) { }
        });
    })

    // Update Item
    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select' + prodid + ' option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
                document.getElementById("subtotal").innerHTML = json.subtotal
            },
            error: function (xhr, errmsg, err) { }
        });
    })
</script>

{% endblock %}